### ISSUE TITLE
Working Demo?

### ISSUE THREAD

**Issue by mikeerickson** [vue-bulma/datepicker#26]
I am looking for a working demo of this component.   Trying to integrate into our app, however, webpack throws a fit.  I have already had to install a slew of `loaders` which shouldn't be required when working with an npm module?

```

> vue-formly-test@1.0.0 build /Users/mikee/Documents/Projects/dev/vue/vue-formly-test
> webpack --progress --colors --hide-modules

Hash: [1m655d16f1ca86bbf1255a[39m[22m
Version: webpack [1m2.2.1[39m[22m
Time: [1m8461[39m[22mms
    [1mAsset[39m[22m    [1mSize[39m[22m  [1mChunks[39m[22m  [1m[39m[22m           [1m[39m[22m       [1mChunk Names[39m[22m
[1m[33mbundle.js[39m[22m  [1m[33m575 kB[39m[22m       [1m0[39m[22m  [1m[32m[emitted][39m[22m  [1m[33m[big][39m[22m  main

[1m[31mERROR in ./~/babel-loader/lib!./~/vue-loader/lib/selector.js?type=script&index=0!./~/vue-bulma-datepicker/src/index.vue
Module not found: Error: Can't resolve './SingleInput' in '/Users/mikee/Documents/Projects/dev/vue/vue-formly-test/node_modules/vue-bulma-datepicker/src'
 @ ./~/babel-loader/lib!./~/vue-loader/lib/selector.js?type=script&index=0!./~/vue-bulma-datepicker/src/index.vue 15:19-43
 @ ./~/vue-bulma-datepicker/src/index.vue
 @ ./src/app.js[39m[22m

[1m[31mERROR in ./~/babel-loader/lib!./~/vue-loader/lib/selector.js?type=script&index=0!./~/vue-bulma-datepicker/src/index.vue
Module not found: Error: Can't resolve './WrapperInput' in '/Users/mikee/Documents/Projects/dev/vue/vue-formly-test/node_modules/vue-bulma-datepicker/src'
 @ ./~/babel-loader/lib!./~/vue-loader/lib/selector.js?type=script&index=0!./~/vue-bulma-datepicker/src/index.vue 19:20-45
 @ ./~/vue-bulma-datepicker/src/index.vue
 @ ./src/app.js[39m[22m

[1m[31mERROR in ./~/flatpickr/dist/flatpickr.js
Module build failed: ReferenceError: Unknown plugin "transform-remove-strict-mode" specified in "/Users/mikee/Documents/Projects/dev/vue/vue-formly-test/node_modules/flatpickr/.babelrc" at 0, attempted to resolve relative to "/Users/mikee/Documents/Projects/dev/vue/vue-formly-test/node_modules/flatpickr"
    at /Users/mikee/Documents/Projects/dev/vue/vue-formly-test/node_modules/babel-core/lib/transformation/file/options/option-manager.js:180:17
    at Array.map (native)
    at Function.normalisePlugins (/Users/mikee/Documents/Projects/dev/vue/vue-formly-test/node_modules/babel-core/lib/transformation/file/options/option-manager.js:158:20)
    at OptionManager.mergeOptions (/Users/mikee/Documents/Projects/dev/vue/vue-formly-test/node_modules/babel-core/lib/transformation/file/options/option-manager.js:234:36)
    at OptionManager.init (/Users/mikee/Documents/Projects/dev/vue/vue-formly-test/node_modules/babel-core/lib/transformation/file/options/option-manager.js:368:12)
    at File.initOptions (/Users/mikee/Documents/Projects/dev/vue/vue-formly-test/node_modules/babel-core/lib/transformation/file/index.js:216:65)
    at new File (/Users/mikee/Documents/Projects/dev/vue/vue-formly-test/node_modules/babel-core/lib/transformation/file/index.js:139:24)
    at Pipeline.transform (/Users/mikee/Documents/Projects/dev/vue/vue-formly-test/node_modules/babel-core/lib/transformation/pipeline.js:46:16)
    at transpile (/Users/mikee/Documents/Projects/dev/vue/vue-formly-test/node_modules/babel-loader/lib/index.js:46:20)
    at Object.module.exports (/Users/mikee/Documents/Projects/dev/vue/vue-formly-test/node_modules/babel-loader/lib/index.js:155:20)
 @ ./~/babel-loader/lib!./~/vue-loader/lib/selector.js?type=script&index=0!./~/vue-bulma-datepicker/src/index.vue 7:17-37
 @ ./~/vue-bulma-datepicker/src/index.vue
 @ ./src/app.js[39m[22m
```

**Comment by luventa** [comment]
Please check. I created this demo for you minutes ago.
https://github.com/luventa/datepicker-demo
